import { ethers } from 'ethers';

const ABI = [
  {
    inputs: [{ internalType: 'string', name: 'baseTokenURI', type: 'string' }, { internalType: 'address', name: 'initialSigner', type: 'address' }],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  { inputs: [], name: 'AlreadyMinted', type: 'error' },
  { inputs: [], name: 'AttestationExpired', type: 'error' },
  { inputs: [], name: 'InvalidSignature', type: 'error' },
  { inputs: [], name: 'InvalidSignatureS', type: 'error' },
  { inputs: [], name: 'NonTransferable', type: 'error' },
  { inputs: [], name: 'NotMinted', type: 'error' },
  { inputs: [], name: 'NotOwner', type: 'error' },
  { inputs: [], name: 'NotPendingOwner', type: 'error' },
  { inputs: [], name: 'TokenDoesNotExist', type: 'error' },
  { inputs: [], name: 'UnauthorizedAttestation', type: 'error' },
  { inputs: [], name: 'ZeroAddress', type: 'error' },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: 'address', name: 'account', type: 'address' }, { indexed: true, internalType: 'uint256', name: 'tokenId', type: 'uint256' }],
    name: 'Burned',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: 'address', name: 'to', type: 'address' }, { indexed: true, internalType: 'uint256', name: 'tokenId', type: 'uint256' }, { indexed: false, internalType: 'uint256', name: 'score', type: 'uint256' }],
    name: 'Minted',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: 'address', name: 'previousOwner', type: 'address' }, { indexed: true, internalType: 'address', name: 'newOwner', type: 'address' }],
    name: 'OwnershipTransferred',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: 'address', name: 'account', type: 'address' }, { indexed: true, internalType: 'uint256', name: 'tokenId', type: 'uint256' }, { indexed: false, internalType: 'uint256', name: 'oldScore', type: 'uint256' }, { indexed: false, internalType: 'uint256', name: 'newScore', type: 'uint256' }],
    name: 'ScoreUpdated',
    type: 'event',
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'balanceOf',
    inputs: [{ internalType: 'address', name: 'account', type: 'address' }],
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'burn',
    inputs: [],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'getMetadata',
    inputs: [{ internalType: 'uint256', name: 'tokenId', type: 'uint256' }],
    outputs: [
      { internalType: 'uint256', name: 'score', type: 'uint256' },
      { internalType: 'uint256', name: 'contractCount', type: 'uint256' },
      { internalType: 'uint256', name: 'verifiedContractCount', type: 'uint256' },
      { internalType: 'bool', name: 'hasENS', type: 'bool' },
      { internalType: 'uint256', name: 'mintedAt', type: 'uint256' },
      { internalType: 'uint256', name: 'updatedAt', type: 'uint256' },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'getTokenByAddress',
    inputs: [{ internalType: 'address', name: 'account', type: 'address' }],
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'hasMinted',
    inputs: [{ internalType: 'address', name: 'account', type: 'address' }],
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'mint',
    inputs: [
      { internalType: 'uint256', name: 'score', type: 'uint256' },
      { internalType: 'uint256', name: 'contractCount', type: 'uint256' },
      { internalType: 'uint256', name: 'verifiedContractCount', type: 'uint256' },
      { internalType: 'bool', name: 'hasENS', type: 'bool' },
      { internalType: 'uint256', name: 'deadline', type: 'uint256' },
      { internalType: 'uint8', name: 'v', type: 'uint8' },
      { internalType: 'bytes32', name: 'r', type: 'bytes32' },
      { internalType: 'bytes32', name: 's', type: 'bytes32' },
    ],
    outputs: [{ internalType: 'uint256', name: 'tokenId', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'name',
    inputs: [],
    outputs: [{ internalType: 'string', name: '', type: 'string' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'owner',
    inputs: [],
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'signer',
    inputs: [],
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'symbol',
    inputs: [],
    outputs: [{ internalType: 'string', name: '', type: 'string' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'totalSupply',
    inputs: [],
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'updateScore',
    inputs: [
      { internalType: 'uint256', name: 'score', type: 'uint256' },
      { internalType: 'uint256', name: 'contractCount', type: 'uint256' },
      { internalType: 'uint256', name: 'verifiedContractCount', type: 'uint256' },
      { internalType: 'bool', name: 'hasENS', type: 'bool' },
      { internalType: 'uint256', name: 'deadline', type: 'uint256' },
      { internalType: 'uint8', name: 'v', type: 'uint8' },
      { internalType: 'bytes32', name: 'r', type: 'bytes32' },
      { internalType: 'bytes32', name: 's', type: 'bytes32' },
    ],
  },
];

export { ABI };
